# Assessments
Name: Tia Plagata

YW
* write a function to find the mean of a list of numbers
* write a function that calculates a dot product
* write a function that centers an array on the mean 
* write a function to calculate the standard deviation of a list of a numbers (preferably using a dot product)
* write a function to calculate the correlation and covariance of two lists
* write a function to calculate the cost between ytrue and ypred

In [3]:
import numpy as np

In [8]:
def mean_center(lst1):
    """
    write a function that takes in a list
    and returns that list but centered on the mean
    
    in other words x -> (x - mu)
    """
    return lst1 - np.mean(lst1)


def dot_product(lst1, lst2):
    """
    write a function that takes in a list 
    of numbers and returns their dot product
    """
    if len(lst1) != len(lst2):
        raise Exception("Vector lengths are not equal")
        return None
    s = 0
    for i in range(len(lst1)):
        p = lst1[i] * lst2[i]
        s += p
    return s

In [10]:
# Test 
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
print(mean_center(lst1))
print(dot_product(lst1, lst2))
# Check
np.dot(lst1, lst2)

[-1.  0.  1.]
32


32

# Standard Deviation Formula
![](images/standard-deviation.png)

In [17]:
def standard_deviation(lst1):
    """
    write a function that takes in a list
    of numbers and returns its standard deviation
    """
    x_bar = mean_center(lst1)
    num = dot_product(x_bar, x_bar)
    denom = len(lst1)
    return np.sqrt(num / denom)

In [18]:
# Test 
lst1 = [1, 2, 3]
print(standard_deviation(lst1))
# Check
np.std(lst1)

0.816496580927726


0.816496580927726

# Covariance Formula
![](images/covariance.png)

In [22]:
def covariance(lst1, lst2):
    """
    write an function that takes in two lists
    of numbers and returns their covariance
    """
    lst1_cent = mean_center(lst1)
    lst2_cent = mean_center(lst2)
    num = dot_product(lst1_cent, lst2_cent)
    denom = len(lst1)
    return num / denom

**Note, in the test below, the covariances are not equal because numpy uses n-1 (for a sample), and the formula above uses n (for a population). To get the covariances to be the same in the test, I would just need to change ```denom = len(lst1) - 1``` in the function above.**

In [23]:
# Test 
lst1 = [1, 2, 3]
lst2 = [3, 4, 5]
print(covariance(lst1, lst2))
# Check
np.cov(lst1, lst2)

0.6666666666666666


array([[1., 1.],
       [1., 1.]])

# Correlation Formula
![](images/correlation.png)

In [28]:
def correlation(lst1, lst2):
    """
    write an function that takes in two lists 
    of numbers and returns their correlation
    """
    x_cent = mean_center(lst1)
    y_cent = mean_center(lst2)
    num = dot_product(x_cent, y_cent)
    denom = np.sqrt(dot_product(x_cent, x_cent) * dot_product(y_cent, y_cent))
    return num / denom

In [29]:
# Test 
lst1 = [1, 2, 3]
lst2 = [3, 4, 5]
print(correlation(lst1, lst2))
# Check
np.corrcoef(lst1, lst2)

1.0


array([[1., 1.],
       [1., 1.]])

# RMSE Formula
![](images/rmse.png)

In [30]:
def rmse(ytrue, ypred):
    """
    write a function that takes in ytrue and ypred
    and returns their root mean squared error
    """
    centered = ypred - ytrue
    num = dot_product(centered, centered)
    denom = len(ytrue)
    return np.sqrt(num / denom)

In [31]:
from sklearn.metrics import mean_squared_error
# Test 
lst1 = np.array([1, 2, 3])
lst2 = np.array([3, 4, 5])
print(rmse(lst1, lst2))
# Check
np.sqrt(mean_squared_error(lst1, lst2))

2.0


2.0

# RSS Formula 
![](images/rss.png)

In [36]:
def rss(ytrue, ypred):
    """
    write a function that takes in ytrue and ypred
    and returns their rss
    """
    centered = ytrue - ypred
    return dot_product(centered, centered)

In [38]:
# Test 
lst1 = np.array([1, 2, 3])
lst2 = np.array([3, 4, 5])
print(rss(lst1, lst2))
# Check
mean_squared_error(lst1, lst2) * len(lst1)

12


12.0